[book]
title = "Tornium"
authors = ["tiksan"]
description = "Documentation and guides covering Tornium and its official userscripts"
src = "src/"
language = "en"
text-direction = "ltr"

[build]
build-dir = "build/"
create-missing = true
use-default-preprocessors = true
extra-watch-dirs = []
